---
- name: Install PECL libaries.
  command: "pecl install {{ item }}"
  register: pecl_result
  changed_when: "pecl_result.rc == 0"
  failed_when: "not (('already installed' in pecl_result.stdout|default()) or ('install ok:' in pecl_result.stdout|default()))"
  with_items: php_pecl_extensions
